name: AWS Deployement

on:
    push:
        branches:
            - main

env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: imagescrapper  

jobs:
    integration:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Python
              uses: actions/setup-python@v2
              with:
                    python-version: 3.9
            - name: Intall Lint Test
              run: make all
    deployement:
        needs: integration
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                aws-region: ${{env.AWS_REGION}}
            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1
            - name: Build, tag and push image to ECR
              id: build-image
              env:
                ECR_REGISTRY:  ${{steps.login-ecr.outputs.registry}}
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:Latest .
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:Latest